"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type User={id:number;name:string;email:string;role:"student"|"tutor"|"admin"};
type ClassItem={id:number;title:string;program:string;description:string;starts_at:string;duration:number;capacity:number;tutor_name:string;meeting_url:string;enrolled:number;attendance?:string};
type Notification={id:number;title:string;message:string;kind:string;is_read:number;created_at:string};
type Person={id:number;name:string;email:string;role:string;country:string;age?:number};
type Data={user:User|null;classes:ClassItem[];myClasses?:ClassItem[];notifications?:Notification[];people?:Person[]};

export default function Home(){
 const [data,setData]=useState<Data>({user:null,classes:[]}); const [page,setPage]=useState<"home"|"classes"|"portal"|"people">("home"); const [authOpen,setAuthOpen]=useState(false); const [register,setRegister]=useState(false); const [notice,setNotice]=useState(""); const [classOpen,setClassOpen]=useState(false); const [loading,setLoading]=useState(true);
 const load=async()=>{const r=await fetch("/api/platform",{cache:"no-store"});setData(await r.json());setLoading(false)}; useEffect(()=>{load()},[]);
 const toast=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(""),3000)};
 const act=async(body:Record<string,unknown>)=>{const r=await fetch("/api/platform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){toast(j.error);return false}await load();return true};
 const unread=data.notifications?.filter(n=>!n.is_read).length||0;
 const nextClass=useMemo(()=>data.myClasses?.[0], [data.myClasses]);
 async function authSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body=Object.fromEntries(f.entries());const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,action:register?"register":"login"})});const j=await r.json();if(!r.ok)return toast(j.error);setAuthOpen(false);setPage("portal");await load();toast(`Welcome, ${j.user.name}!`)}
 async function logout(){await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});setPage("home");await load()}
 async function classSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(await act({...f,action:"createClass",startsAt:`${f.date}T${f.time}:00`})){setClassOpen(false);toast("Class created and saved.")}}
 return <main className="platform">
  {notice&&<div className="toast">✓ {notice}</div>}
  <header className="topbar"><button className="brand" onClick={()=>setPage("home")}><span className="brandmark">E</span><span>Equal Access<br/><b>Robotics</b></span></button><nav>{(["home","classes","portal"] as const).map(x=><button key={x} className={page===x?"active":""} onClick={()=>x==="portal"&&!data.user?setAuthOpen(true):setPage(x)}>{x==="portal"&&data.user?"My portal":x}</button>)}{data.user?.role==="admin"&&<button className={page==="people"?"active":""} onClick={()=>setPage("people")}>People</button>}</nav><div className="headerActions">{data.user?<><button className="notifyButton" onClick={async()=>{setPage("portal");await act({action:"readNotifications"})}}>◉{unread>0&&<b>{unread}</b>}</button><span className="avatar">{data.user.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span className="profile">{data.user.name}<small>{data.user.role}</small></span><button className="signout" onClick={logout}>Sign out</button></>:<button className="primary compact" onClick={()=>setAuthOpen(true)}>Sign in</button>}</div></header>

  {page==="home"&&<><section className="hero"><div className="heroCopy"><span className="eyebrow">BUILDING FUTURES SINCE 2020</span><h1>Code is a language.<br/><em>Everyone deserves to speak it.</em></h1><p>Free, live coding and robotics classes led by dedicated volunteer tutors—wherever a young creator calls home.</p><div className="heroButtons"><button className="primary" onClick={()=>setPage("classes")}>Find a class →</button><button className="textBtn" onClick={()=>{setRegister(true);setAuthOpen(true)}}>Join our community</button></div></div><div className="heroArt"><div className="sun"/><div className="codeCard">&lt; hello<br/><b>&nbsp; future /&gt;</b></div><div className="robot"><i/><span>•‿•</span></div><div className="kid one">✦</div><div className="kid two">⌁</div></div></section><section className="impactStrip"><div><strong>1,000+</strong><span>young creators</span></div><div><strong>40</strong><span>volunteer tutors</span></div><div><strong>16</strong><span>countries reached</span></div><div><strong>100%</strong><span>free to learn</span></div><p>Every number is a story<br/><b>still being written.</b></p></section><section className="workspace"><div className="pageHeading"><div><span className="eyebrow">HOW IT WORKS</span><h2>A place to learn, teach, and belong.</h2></div></div><div className="programGrid"><article className="programCard"><span>01</span><h3>Create your profile</h3><p>Join as a student or volunteer tutor. Your personal portal keeps everything organized.</p></article><article className="programCard"><span>02</span><h3>Choose a class</h3><p>Browse live coding and robotics sessions and enroll in the right learning path.</p></article><article className="programCard"><span>03</span><h3>Learn together</h3><p>Join lessons, access resources, receive reminders, and track attendance.</p></article><article className="programCard"><span>04</span><h3>Build the future</h3><p>Turn new skills into websites, games, robots, and lasting confidence.</p></article></div></section></>}

  {page==="classes"&&<section className="workspace"><div className="pageHeading"><div><span className="eyebrow">LIVE LEARNING</span><h2>Upcoming classes</h2><p>Times are shown in your local timezone. Sign in as a student to save your place.</p></div>{data.user&&["admin","tutor"].includes(data.user.role)&&<button className="primary compact" onClick={()=>setClassOpen(true)}>+ Create class</button>}</div><div className="classCatalog">{loading?<p>Loading classes…</p>:data.classes.map(c=><article className="classCard" key={c.id}><div className="classTop"><span>{c.program}</span><b>{c.enrolled}/{c.capacity} enrolled</b></div><h3>{c.title}</h3><p>{c.description}</p><div className="classMeta"><span>◷ {new Date(c.starts_at).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}</span><span>♧ {c.tutor_name||"Tutor needed"}</span><span>⌛ {c.duration} minutes</span></div>{data.user?.role==="student"?<button className="primary" onClick={async()=>{if(await act({action:"enroll",classId:c.id}))toast("You’re enrolled! Check your portal.")}}>Enroll now →</button>:!data.user?<button className="primary" onClick={()=>setAuthOpen(true)}>Sign in to enroll</button>:<span className="roleNote">Available to student accounts</span>}</article>)}</div></section>}

  {page==="portal"&&data.user&&<section className="workspace portalWrap"><div className="portalWelcome"><div><span className="eyebrow">{data.user.role.toUpperCase()} PORTAL</span><h2>Welcome back, {data.user.name.split(" ")[0]}.</h2><p>{data.user.role==="student"?"Keep learning. Your next big idea starts here.":data.user.role==="tutor"?"Your students are ready to build something wonderful.":"Here’s the pulse of Equal Access Robotics."}</p></div>{["admin","tutor"].includes(data.user.role)&&<button className="primary" onClick={()=>setClassOpen(true)}>+ Create a class</button>}</div><div className="portalGrid"><section className="panel"><div className="panelHead"><div><h3>{data.user.role==="student"?"My learning":"My classes"}</h3><p>{data.myClasses?.length||0} active classes</p></div><button onClick={()=>setPage("classes")}>Browse all →</button></div>{!data.myClasses?.length?<div className="emptyState"><b>No classes yet</b><p>Browse the schedule to get started.</p></div>:data.myClasses.map(c=><div className="portalClass" key={c.id}><div><span className="coursePill">{c.program}</span><h3>{c.title}</h3><p>{new Date(c.starts_at).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})} · {c.duration} min</p></div>{c.meeting_url?<a className="joinButton" href={c.meeting_url} target="_blank" rel="noreferrer">Join lesson ↗</a>:<span className="roleNote">Link coming soon</span>}</div>)}</section><aside className="panel notificationPanel"><div className="panelHead"><div><h3>Notifications</h3><p>{unread} unread</p></div></div>{!data.notifications?.length?<div className="emptyState">You’re all caught up.</div>:data.notifications.map(n=><div className={`notification ${n.is_read?"read":""}`} key={n.id}><i>{n.kind==="success"?"✓":"◷"}</i><span><b>{n.title}</b><p>{n.message}</p><small>{new Date(n.created_at+"Z").toLocaleDateString()}</small></span></div>)}</aside></div>{nextClass&&<div className="nextBanner"><span>UP NEXT</span><h3>{nextClass.title}</h3><p>{new Date(nextClass.starts_at).toLocaleString([], {dateStyle:"full",timeStyle:"short"})}</p></div>}</section>}

  {page==="people"&&data.user?.role==="admin"&&<section className="workspace"><div className="pageHeading"><div><span className="eyebrow">COMMUNITY DATABASE</span><h2>Students & tutors</h2><p>{data.people?.length} registered people. Account data is saved locally.</p></div></div><article className="panel"><div className="studentTable"><div className="tableRow tableHeader"><span>Person</span><span>Role</span><span>Age</span><span>Country</span><span>Email</span></div>{data.people?.map(p=><div className="tableRow" key={p.id}><span><i className="studentAvatar">{p.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</i><b>{p.name}</b></span><span><b className={`rolePill ${p.role}`}>{p.role}</b></span><span>{p.age||"—"}</span><span>{p.country||"—"}</span><span>{p.email}</span></div>)}</div></article></section>}

  <section className="mission"><span className="eyebrow">OUR PROMISE</span><h2>Talent is everywhere.<br/><em>Opportunity should be too.</em></h2><p>From online tutoring to in-person robotics labs, we remove barriers between young people and the technology shaping their world.</p></section><footer><div className="brand"><span className="brandmark">E</span><span>Equal Access<br/><b>Robotics</b></span></div><p>Teaching the next generation to build the future.</p><small>© 2026 Equal Access Robotics</small></footer>

  {authOpen&&<div className="modalBack" onMouseDown={()=>setAuthOpen(false)}><form className="modal authModal" onSubmit={authSubmit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setAuthOpen(false)}>×</button><span className="eyebrow">{register?"JOIN EAR":"WELCOME BACK"}</span><h2>{register?"Create your account":"Sign in to your portal"}</h2>{register&&<><label>Full name<input name="name" required/></label><div className="formRow"><label>I am a<select name="role" defaultValue="student"><option value="student">Student</option><option value="tutor">Volunteer tutor</option></select></label><label>Country<input name="country" required/></label></div></>}<label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={8} required/></label><button className="primary" type="submit">{register?"Create account":"Sign in"}</button><button className="switchAuth" type="button" onClick={()=>setRegister(!register)}>{register?"Already registered? Sign in":"New here? Create an account"}</button>{!register&&<div className="demoBox"><b>Demo accounts · password: demo1234</b><span>Student: amara@example.com</span><span>Tutor: maya@equalaccess.org</span><span>Admin: admin@equalaccess.org</span></div>}</form></div>}
  {classOpen&&<div className="modalBack" onMouseDown={()=>setClassOpen(false)}><form className="modal" onSubmit={classSubmit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setClassOpen(false)}>×</button><span className="eyebrow">NEW CLASS</span><h2>Plan a live lesson</h2><label>Class title<input name="title" required placeholder="Python Pioneers"/></label><label>Program<select name="program"><option>Python</option><option>Web Development</option><option>Robotics</option><option>Scratch</option></select></label><label>Description<input name="description" required/></label><div className="formRow"><label>Date<input name="date" type="date" required/></label><label>Time<input name="time" type="time" required/></label></div><div className="formRow"><label>Duration<input name="duration" type="number" defaultValue="60"/></label><label>Capacity<input name="capacity" type="number" defaultValue="10"/></label></div><label>Meeting or lesson URL<input name="meetingUrl" type="url" placeholder="https://..."/></label><button className="primary" type="submit">Save class</button></form></div>}
 </main>
}
